name: checkmate
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  table_calendar: ^3.0.9
  dart_openai: ^1.9.1
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.19
  animations: ^2.0.7
  dynamic_color: ^1.6.3
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
