name: checkmate
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  table_calendar: ^3.0.9
  flutter_local_notifications: ^13.0.0
  animations: ^2.0.7
  dynamic_color: ^1.6.3
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.2.2
  google_sign_in: ^6.1.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  animated_snack_bar: ^0.3.0
  fl_chart: ^0.62.0
  localstorage: ^4.0.1+2
  intl: ^0.18.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_w.png
  android: true
  android_12:
    background_color: "#FFFFFF"
    foreground_image: assets/images/logo_w.png
    foreground_image_dark: assets/images/logo_w.png
  ios: true
  web: false

flutter:
  assets:
    - assets/images/
    - assets/google_fonts/

  uses-material-design: true
