// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI56rNg2eIK5FneNH1rfPo1ssWyHvaevg',
    appId: '1:515699661812:web:d723760abdd45148e137a1',
    messagingSenderId: '515699661812',
    projectId: 'checkmate-5875e',
    authDomain: 'checkmate-5875e.firebaseapp.com',
    storageBucket: 'checkmate-5875e.appspot.com',
    measurementId: 'G-H7HK2YH9SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENEJ-ZkLEGiXC79jN8I46gNoFNf12xGA',
    appId: '1:515699661812:android:ebe229091ae662f8e137a1',
    messagingSenderId: '515699661812',
    projectId: 'checkmate-5875e',
    storageBucket: 'checkmate-5875e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6SK2i-3llZgq528PTJfOOLsdBOdkogU',
    appId: '1:515699661812:ios:b24e4259693635e7e137a1',
    messagingSenderId: '515699661812',
    projectId: 'checkmate-5875e',
    storageBucket: 'checkmate-5875e.appspot.com',
    iosClientId: '515699661812-7u56mjub79u6fvg2eemlgnq9vjflk3mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkmate',
  );
}
