name: Flutter application testing
on:
  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Flutter test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test  รอเขียน test case
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: test-app.apk
          path: build/app/outputs/flutter-apk/app-release.apk
  # build:
